version: '3.7'

services:
  app:
    image: nodeapp
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - mongodb

  mongodb:
    image: 'mongo'
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=demo # database name you want to make
      - MONGO_INITDB_ROOT_USERNAME=root # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=secret # set your contatner root password
    ports:
      - '27017-27019:27017-27019'
    networks:
      - nodeapp-network


networks:
  nodeapp-network:
    driver: bridge